In [1]:
import numpy as np

In [4]:
X=np.array([[1,0,0],[1,0,1],[1,1,0],[1,1,1]])
Y=np.array([[0,1,1,0]])
V=np.random.random((3,4))*2-1
W=np.random.random((4,1))*2-1
print(V)
print(V)
lr=0.11
def sigmoid(x):
    return 1/(1+np.exp(-x))
def dsigmoid(x):
    return x*(1-x)
def update():
    global X,Y,V,W,lr
    L1=sigmoid(np.dot(X,V))
    L2=sigmoid(np.dot(L1,W))
    L2_delta=(Y.T-L2)*dsigmoid(L2)
    L1_delta=L2_delta.dot(W.T)*dsigmoid(L1)
    W_C=lr*L1.T.dot(L2_delta)
    V_C=lr*X.T.dot(L1_delta)
    W=W+W_C
    V=V+V_C


[[-0.64120167  0.06261755 -0.81850333 -0.0639941 ]
 [-0.955851    0.94369703  0.49572207  0.35198362]
 [ 0.04247147 -0.01948391 -0.74992854 -0.40039558]]
[[-0.64120167  0.06261755 -0.81850333 -0.0639941 ]
 [-0.955851    0.94369703  0.49572207  0.35198362]
 [ 0.04247147 -0.01948391 -0.74992854 -0.40039558]]


In [6]:
a=np.random.randn(3)#标准正态分布
b=np.random.rand(3)#[0,1)均匀分布
c=np.random.random(3)#[0.0, 1.0)连续均匀分布
print(a)
print(b)
print(c)

[ 0.12653849 -0.28215122  0.22100687]
[ 0.16225166  0.3670434   0.65392667]
[ 0.95925755  0.37138346  0.8101289 ]


In [8]:
for i in range(20000):
    update()
    if i%500==0:
        L1=sigmoid(np.dot(X,V))
        L2=sigmoid(np.dot(L1,W))
        print('error:',np.mean(np.abs(Y.T-L2)))
L1=sigmoid(np.dot(X,V))
L2=sigmoid(np.dot(L1,W))
print(L2)
def judge(x):
    if x>=0.5:
        return 1
    else:
        return 0
for i in map(judge,L2):
    print(i)


error: 0.0230928073986
error: 0.0227421803954
error: 0.0224062924431
error: 0.022084156749
error: 0.0217748757252
error: 0.0214776309465
error: 0.0211916744493
error: 0.0209163211665
error: 0.0206509423277
error: 0.0203949596834
error: 0.0201478404334
error: 0.0199090927617
error: 0.019678261894
error: 0.0194549266064
error: 0.0192386961273
error: 0.0190292073802
error: 0.0188261225236
error: 0.0186291267529
error: 0.0184379263303
error: 0.0182522468161
error: 0.0180718314773
error: 0.0178964398536
error: 0.0177258464614
error: 0.0175598396223
error: 0.0173982204005
error: 0.0172408016384
error: 0.0170874070796
error: 0.0169378705703
error: 0.01679203533
error: 0.0166497532867
error: 0.0165108844671
error: 0.016375296439
error: 0.0162428637995
error: 0.0161134677049
error: 0.0159869954378
error: 0.0158633400095
error: 0.0157423997926
error: 0.015624078182
error: 0.015508283282
error: 0.0153949276164
[[ 0.01439424]
 [ 0.98565353]
 [ 0.98357579]
 [ 0.01597167]]
0
1
1
0
